org: manishachoudhary12
service: cloudkart-serverless-Product-Inventory-System

frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    PRODUCTS_TABLE: CloudKartProducts

functions:
  createProduct:
    handler: index.createProduct
    events:
      - http:
          path: /products
          method: post

resources:
  Resources:
    CloudKartProducts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CloudKartProducts
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


